### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by DanielRuf** [knq/chrome-headless#1]
It seems Chrome uses Russian. At least I get a screenshot with russian text when I try graphcool/chromeless.

Can you reproduce this?

**Comment by kenshaw** [comment]
Are you using this to build Chrome? Chances are you need to reconfigure the default locales on your system -- make sure you have setup/configured all the correct dependencies on Linux using the scripts from the Chromium source tree.

**Comment by DanielRuf** [comment]
The system (a root server with Debian) is in English. I used the provided Docker image, I did not build Chrome myself.

**Comment by kenshaw** [comment]
I really don't know what the cause / issue is. The default language I'm seeing is definitely english.

**Comment by DanielRuf** [comment]
I've run `docker rmi` and a fresh `docker pull`. Still the same. A simple `curl www.google.com` redirects me to the german version, not the russian. So I still think it is an issue in the image.

This is the output of a fresh install:

```
docker exec -it chrome-headless /bin/bash -c "curl www.google.com"                                                    <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=vluBWaLHL4u0gQS2priwDQ">here</A>.
</BODY></HTML>
```

At least cyrillic and looks like Russian to me. It's actually a language used in Ukraine.

**Comment by DanielRuf** [comment]
cc @blitznote

**Comment by DanielRuf** [comment]
Bug in the base image of @Blitznote

**Comment by DanielRuf** [comment]
Or should the chrome-headless install and set the locale?

**Comment by DanielRuf** [comment]
It seems forcing curl to use OPv4 reproduces this. Closing the issue, bug is on the side of Google (again).

**Comment by kenshaw** [comment]
Thanks, appreciate the followup on this.
